blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Blacksuan19/varo-believe-to-monarch/discussions
    about: Ask questions or share how you're using the tool
